name: haplotyping-kiv2-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pysam>=0.22
  - pandas>=2.0
  - edlib>=1.3
  - samtools>=1.18
  - mafft>=7.5
  - pip
  - pip:
      - argparse
